### ISSUE TITLE
Replace TravisCI with CircleCI

### ISSUE THREAD

**Issue by markusguenther** [Unikka/neos-slick#10]
After TravisCI has been acquired and the company fired a lot of the awesome developers we should switch to CircleCI. Don´t want to support such behavior.

**Comment by breadlesscode** [comment]
Maybe we can try Github Actions here?

**Comment by markusguenther** [comment]
Can give it a try :)

I am already permitted as single user ... but guess have not the beta feature for the organisation yet.

**Comment by markusguenther** [comment]
Thank you @Virtim for taking care. Just adjusted the settings to special branches. :)
But you could not know that :)
