### ISSUE TITLE
It is not possible to add an slide element on neos 5.2.2

### ISSUE THREAD

**Issue by benediktrillox** [Unikka/neos-slick#196]
### Description

After the installation with composer it is not possible to add an slide to the silder element.
Because the "slide element" is not showing up after i have created and slider element on my document tree.
It seem that the slider element is also not an content collection.

### Steps to Reproduce

1. install it with composer and neos 5.0
2. open some page and add a slider element
3. try to add an slide element

#### Expected behavior

After i have added an slider it should be possible to add an slide element.

#### Actual behavior

[What actually happened]

### Affected Versions

Neos: 5.2.2

Slick: v3.3.2

You can get this information by running `composer show` or using the package management module within Neos.

**Comment by markssarGit** [comment]
No slide element options in node menu. 
Affected version:
Neos: 5.3.1
Slic slider v. 3.4

**Comment by markusguenther** [comment]
Sorry for not responding that long ... just did not see this and obviously miss the mail.
Need to test that first, but as the neos major release is happen shortly I can not promise that I will make it this week.

Thanks for reporting that ❤️

**Comment by markusguenther** [comment]
Hmm tested that now with neos 5.3 and the slider 3.4.1 and it works. Need to check neos 5.2 also if there is a possible problem. https://neos-project.slack.com/archives/C050C8FEK/p1607546425453300?thread_ts=1607514879.436800&cid=C050C8FEK

**Comment by markusguenther** [comment]
Tested the package today on neos 5.2 and it just works. Will close the issue.
If this is still relevant for you, feel free to reopen the issue with some additional information.

Thanks for the report 🙏
