### ISSUE TITLE
Typos in responsive mixin (file) names

### ISSUE THREAD

**Issue by lorenzulrich** [Unikka/neos-slick#39]
### Description

The responsive mixins have a typo in their files and node type names:

`NodeTypes.Mixin.Repsonsive.Lg.yaml` instead of `NodeTypes.Mixin.Responsive.Lg.yaml` (and so on)

I intended to fix this via a PR, but it is a breaking change, so I don't know if it can be fixed without releasing a major version.

**Comment by breadlesscode** [comment]
Yes you are right. Please make a PR ;) We will release a new Major Version :)
